### PR TITLE
bug: 🐛 data quality modal title fix

### PR DESCRIPTION
**Pull request by snenenenenenene**

### CODE REVIEW

**Review by aliokan — CHANGES_REQUESTED** [review]
Could you please test your change before submit for review :pray: 

image

**Comment by snenenenenenene** [comment]
@aliokan I can't figure out why the session page isn't working for this branch :/

**Review by LBONTEN — COMMENTED** [review]
Unable to test this using the DEV environment. Since there are no agenda items without titles present. Will try again once the QA environment is back.

**Review by aliokan — APPROVED** [review]
@snenenenenenene I made the following modifications: 
- I revert the modification in utils/array-utils, and filter out agenda items that do not have title https://github.com/lblod/frontend-burgernabije-besluitendatabank/pull/180/commits/6729413232f75d0e73eaecf23b249cadd9fcd894
- I move the fallback title logic in the model instead of template to avoid repetition https://github.com/lblod/frontend-burgernabije-besluitendatabank/pull/180/commits/282f18b6d35fc7dbdc511b7c32bc51b1770656d0

**Pull request merged**
