### PR TITLE
refactor: :speech_balloon: updated text

### PR DESCRIPTION
**Pull request by snenenenenenene**

### CODE REVIEW

**Review by aliokan — CHANGES_REQUESTED** [review]
@snenenenenenene Can you put list elements in a list? 

image


image

**Review by aliokan — CHANGES_REQUESTED** [review]
@snenenenenenene On wild screen, the scrollbar is disabled
image

**Comment by snenenenenenene** [comment]
@aliokan fixed scroll!

**Review by aliokan — APPROVED** [review]
Looks good! :ok_hand:

**Pull request merged**
