### PR TITLE
feat: :sparkles: added a new hasVotes in the vote component

### PR DESCRIPTION
**Pull request by snenenenenenene**
- added a new hasVotes get in votes as I thought it'd be more consolidated in the vote model
- kept the rest of the hasVotes gets in case I stepped on toes

### CODE REVIEW

**Review by aliokan — CHANGES_REQUESTED** [review]
As discuss during standup, we want to still display the vote when there is not numbers.

**Comment by snenenenenenene** [comment]
@aliokan fixed it!

**Review by aliokan — CHANGES_REQUESTED** [review]
Changes are good, I still have a blocker regarding hidden voters table based on `hasVoteNumbers` value

**Comment by snenenenenenene** [comment]
Fixed it @aliokan

**Review by aliokan — APPROVED** [review]
The modification looks good. LGTM! :pray:

**Pull request merged**
