### PR TITLE
feat: :sparkles: added hasVotersData (name up to discussion)

### PR DESCRIPTION
**Pull request by snenenenenenene**
- added new hasVotersData getter

### CODE REVIEW

**Comment by snenenenenenene** [comment]
@aliokan right now I'm kind of indecisive on how we should handle empty columns. What's your opinion?

image

**Comment by aliokan** [comment]
@snenenenenenene The same as Jodi ;)

**Review by aliokan — APPROVED** [review]
Tested locally, it works as it should ! :+1:

**Comment by aliokan** [comment]
@snenenenenenene Can you mark the PR as ready, or merge it on master :rocket:

**Pull request merged**
