### PR TITLE
Hide Load more button if no more data is available

### PR DESCRIPTION
**Pull request by Denperidge**
Implemented through letting the loadMore actions return a boolean! It feels like a bit of a weird solution but it works so hey

### CODE REVIEW

**Review by aliokan — COMMENTED** [review]
**Question:** What do you think to use total amount of items provided by the server, instead the current workaround? 
A PR is ready to add the missing information : https://github.com/lblod/app-burgernabije-besluitendatabank/pull/14

**Comment by Denperidge** [comment]
That works I guess! I'll wait with merging

**Comment by Denperidge** [comment]
Paused until https://github.com/lblod/app-burgernabije-besluitendatabank/pull/14 merge

**Comment by Denperidge** [comment]
@aliokan I was under the assumption that I would wait until the app pr merge, but do you perhaps prefer to first try @Windvis ' approach?

**Comment by aliokan** [comment]
@Denperidge Both solutions looks good to me. https://github.com/lblod/app-burgernabije-besluitendatabank/pull/14 is merged and deployed

**Pull request closed without merging**
