### PR TITLE
feat(agenda-item): Update `wasHandled` computation

### PR DESCRIPTION
**Pull request by aliokan**
Use session `startedAt` and `endedAt` instead of handledBy value. 

Related to https://binnenland.atlassian.net/browse/BNB-335

## Before

image

## After

image

### CODE REVIEW

**Review by LBONTEN — CHANGES_REQUESTED** [review]
Looks good. But the displayed text should maybe be changed to "Besluit niet beschikbaar" instead of "Dit agendapunt werd nog niet behandeld"

**Comment by aliokan** [comment]
@LBONTEN Based on yesterday discussion, the "Dit agendapunt werd nog niet behandeld' will be completely removed.

**Comment by aliokan** [comment]
@LBONTEN A new version is available:
- it improve session selection to use in priority session with municipality and start date; 
- remove `Dit werd nog niet behandeld` alert

**Review by LBONTEN — APPROVED** [review]
Looks good

**Pull request merged**
